version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: nfl_data
      DB_USER: nfl_user
      DB_PASSWORD: nfl_password
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nfl_data
      POSTGRES_USER: nfl_user
      POSTGRES_PASSWORD: nfl_password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
